-   id: jshint
    name: jshint
    description: ''
    entry: jshint
    language: node
    'types': [javascript]
    args: []
    require_serial: false
    additional_dependencies: ["jshint@2.13.6"]
    minimum_pre_commit_version: '0'
